language: python

python:
- '3.7'

script:
- sh run_tests.sh
branches:
  only:
  - master
  - develop
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  provider: pypi
  user: keotl
  password:
    secure: "Nt8QXOv74rR+v28De1flunkbAosy1ph+CZH7uPJHOCbv+rLfrrMdzMRQjrjoujl8mZ6WJ3GiNYZH6vrYrvIzu99N/v5Bb/b0AC81I4wSWs+v8oTzkDzoxgAmX22ryctB6IfNdM/j2EqYR3Y/ElkG1txDnj1H/1QGkUAPkNnGlFlQS1x8VLh/c/4JZ6PCINMA7H8AYD+INlb/seAyzEXEKhZn4FrYp96P7E8YEJC+tHGFHM/imK8DNr6hFBSf1gcKgkST69k5K6a+3EhFz16zZpzVCBwNjutD2aSP7XcS8us8oIiKIiotmLAEueTWqSIB85Z7LZCxMJTkTGfv+l3TgE+rxN1fqOytyUKbaE+HH55yCMFliRO+aKJ6mu+e+P6HCzR0FvRe3RVst1929knYDzN/grDTvoA7iBAEzQYbSznfWsu/FBGKJSIg1H5/MvQC24accrtu6cGY9BiBSh608j3rrFFolWS6x4FIetFI6h/8sFZo0n0IDBTVqDA942UwCD+kfEKCpi8SBQMrL95jOmi/ix0DJl5l0Chy6EMpHwUHhmFkUlebSxPUzLABEWRyUkY17O2TBhAvZPaoCDnjA5NjCuW5q00wkHdeHH5of2ZPp/voDu/zg36nn9psQq+IY2BwK2dSmf3Eucdi4G6Im9LdgGwAS0MBc1MPq2vOy8w="
  on:
    tags: true
    repo: keotl/anachronos
